// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntqzwatufflkmduktcot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cXp3YXR1ZmZsa21kdWt0Y290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzM3NDQsImV4cCI6MjA2MTYwOTc0NH0.DflPRo6ylepmU6jjobvTDaK5Cusd9VxVwbcjCE28J1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);